# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e15bd5c028911892c2553f160151e315238e913d22764c4350afc78c16c4f582bade540fb08adb903a15f749aaf9870dd127d74cff048cb2df2e3eba62383f

test:
  secret_key_base: 5d285eb289c5e7ec18ac481674dde0b9a3e748626f95dacd2e7d7b48dd7740a7cc30e3576f321b62a85abb314972806835b7da918d8cf3dbf74a0912805bf1fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
